### ISSUE TITLE
Issue with most basic option translation on newer releases

### ISSUE THREAD

**Issue by svrnhdl** [yihong0618/bilingual_book_maker#404]
I just set up this repo on a new machine, and I can't get the most basic example to work with anything other than v0.7.0.

`python3 make_book.py --book_name test_books/animal_farm.epub --openai_key $key  --test --language nl`

/home/thibaut/repos/bilingual_book_maker/venv/lib/python3.11/site-packages/ebooklib/epub.py:1423: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'
  for root_file in tree.findall('//xmlns:rootfile[@media-type]', namespaces={'xmlns': NAMESPACES['CONTAINERNS']}):
  0%|                                                                                                                       | 0/10 [00:00<?, ?it/s]
Animal Farm: A Fairy Story
Connection error.
NoneType takes no arguments
you can resume it next time

This is kind of unintuitive. It works fine on v0.7.0.

**Comment by yihong0618** [comment]
will check it today

**Comment by h9nara** [comment]
我也碰到一样的问题
···
python3 make_book.py --book_name test_books/book_name_redacted.epub --model google
/opt/homebrew/lib/python3.12/site-packages/ebooklib/epub.py:1423: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/xmlns:rootfile[@media-type]'
  for root_file in tree.findall('//xmlns:rootfile[@media-type]', namespaces={'xmlns': NAMESPACES['CONTAINERNS']}):
0it [00:00, ?it/s]
0it [00:00, ?it/s]
···
奇怪的是我转了第一本书，然后成功了， 然后当我要转第二本书的时候就遇到这个错误了
